version: '3.1'

#volumes:
#  pg_data:
#    external: true

services:

  pg_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=q
      - POSTGRES_USER=u
#      - POSTGRES_DB=stage2
    ports:
      - ${POSTGRES_PORT:-5432}:5432
#    volumes:
#      - pg_data:/var/lib/postgresql/data
#      - ./pg_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
